SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE FROM MEMBER_PROFILE
WHERE TLNO != 'NULL' AND GENDER = 'W' AND DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03'

# %Y - %m month와 day를 소문자로 표기하기